### ISSUE TITLE
[BUG] - PDF.js is always downloaded when running run_windows.bat, even if it's already installed

### ISSUE THREAD

**Issue by Harvester62** [Cinnamon/kotaemon#336]
### Description

Running run_windows.bat always re-download the PDF.js library

After the first start up of Agent-Zero and the PDF.js library has been downloaded and properly installed, at any subsequent run of the run_windows.bat file the PDF.js library is downloaded again despite it's already installed, generating a wall of errors in the console (obviously, because it finds the file were already installed), and the program starts without other errors. 

It would be advisable to add a check in the run_windows.bat file for the existance of the PDF.js library, before downloading it.

![immagine](https://github.com/user-attachments/assets/c2185a45-755c-4788-b1cd-acb173827dfd)

... wall of errors ...

![immagine](https://github.com/user-attachments/assets/f489abdd-2fdf-4284-b3c3-c8128415f5d0)

### Reproduction steps

```bash
1. Go to '\kotaemon-app\scripts\'
2. Double click on 'run_windows.bat'
3. The PDF.js library is downloaded despite being already installed
4. See errors
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### Browsers

Firefox

### OS

Windows

**Comment by taprosoft** [comment]
Fixed in this new release https://github.com/Cinnamon/kotaemon/releases/tag/v0.5.3
Please check.

**Comment by Harvester62** [comment]
Thank you very much, @taprosoft , for looking into this issue. Unfortunately, I am still getting the same behavior and errors after updating with update_windows.bat to v0.5.3. The PDF.js was downloaded but, apparently, when unpacking the data it finds all the files as already existing, therefore generating the errors. How can I help you debug this further? Let me know.

**Comment by Harvester62** [comment]
Hmm, after further investigations it appears that the local copy of run_windows.bat has not been synced with the latest version in the main repo, despite I did run the update_windows.bat file without a single warning or error. This is strange.

Reinstalling from scratch worked fine and the problem is fixed, thank you.

**Comment by taprosoft** [comment]
@Harvester62 might be another issue with update script. Can you verify by manually download the new version and create new issue for the update script?

**Comment by Harvester62** [comment]
Sure, I will do it at the next update to 0.5.4.
